# Generated by Django 2.2.19 on 2022-11-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221118_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='decription',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
