# Generated by Django 2.2.19 on 2022-11-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221119_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='decription',
            new_name='description',
        ),
    ]
